name: driver_app
description: A professional Flutter driver app for real-time bus tracking system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Authentication
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  
  # Location Services
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # HTTP Requests
  http: ^1.1.2
  
  # Maps
  google_maps_flutter: ^2.5.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # Other utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
  
  # Add any fonts here if needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf