// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRVtMxN249SUuZgYmQSoVub-_qrm2YC0',
    appId: '1:894410278269:web:your-web-app-id',
    messagingSenderId: '894410278269',
    projectId: 'trackmyride123',
    authDomain: 'trackmyride123.firebaseapp.com',
    storageBucket: 'trackmyride123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJ_-DXjeM70OjziCBG2U7ini-5QDOeVc',
    appId: '1:894410278269:android:5529508223d660be93b814',
    messagingSenderId: '894410278269',
    projectId: 'trackmyride123',
    storageBucket: 'trackmyride123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhRVtMxN249SUuZgYmQSoVub-_qrm2YC0',
    appId: '1:894410278269:ios:your-ios-app-id',
    messagingSenderId: '894410278269',
    projectId: 'trackmyride123',
    storageBucket: 'trackmyride123.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhRVtMxN249SUuZgYmQSoVub-_qrm2YC0',
    appId: '1:894410278269:macos:your-macos-app-id',
    messagingSenderId: '894410278269',
    projectId: 'trackmyride123',
    storageBucket: 'trackmyride123.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhRVtMxN249SUuZgYmQSoVub-_qrm2YC0',
    appId: '1:894410278269:windows:your-windows-app-id',
    messagingSenderId: '894410278269',
    projectId: 'trackmyride123',
    storageBucket: 'trackmyride123.appspot.com',
  );
}